name: Run test on all code

on:
  push:
    branches:
      - master

jobs:
  test-repo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Run test
        run: |
          ls -d day* | while read dir; do cd $dir; echo "Testing $dir"; python -m unittest discover; cd ..; done